spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres_db
    platform: postgres
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: '1.0'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

test:
  name: "hello micro service updated config data againe"
